#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Copy correct snappyHexMeshDict
cp system/snappyHexMeshDict-AL system/snappyHexMeshDict

scripts/Allrun.pre
runApplication $(getApplication)
runApplication vorticity
python scripts/gensampledict.py
runApplication sample -latestTime

# Move post processed data
mkdir -p processed
cp -rfT postProcessing processed/BR
